export const rdapRolePermossionMock = [{
rolepermissionextrapinmock:{
    isAdd:false,
    isEdit:true,
    isDelete:true,
    isView:false,
    module:"extrapin"
},
rolepermissionproductmock:{
    isAdd:true,
    isEdit:false,
    isDelete:true,
    isView:false,
    module:"product"
},
rolepermissionmanagepinmock:{
    isAdd:true,
    isEdit:true,
    isDelete:true,
    isView:true,
    module:"managepin"
},
rolepermissiondependencymock:{
    isAdd:true,
    isEdit:true,
    isDelete:true,
    isView:false,
    module:"dependency"
},
rolepermissiontesterplanmock:{
    isAdd:true,
    isEdit:true,
    isDelete:true,
    isView:false,
    module:"testerplan"
},
rolepermissionsetitemmock:{
    isAdd:true,
    isEdit:true,
    isDelete:true,
    isView:false,
    module:"setitem"
},
rolepermissioncabinetmock:{
    isAdd:true,
    isEdit:true,
    isDelete:true,
    isView:false,
    module:"cabinet"
},
rolepermissionmilestonemock:{
    isAdd:true,
    isEdit:true,
    isDelete:true,
    isView:false,
    module:"milestone"
},
rolepermissionclaritymock:{
    isAdd:true,
    isEdit:true,
    isDelete:true,
    isView:false,
    module:"clarity"
},
rolepermissionlinkedpinmock:{
    isAdd:true,
    isEdit:true,
    isDelete:true,
    isView:false,
    module:"linkedpin"
},
rolepermissionimpactedpinmock:{
    isAdd:true,
    isEdit:true,
    isDelete:true,
    isView:false,
    module:"impactedpin"
},
rolepermissionauditlogmock:{
    isAdd:true,
    isEdit:false,
    isDelete:true,
    isView:false,
    module:"auditlog"
},
rolepermissionversionmock:{
    isAdd:true,
    isEdit:true,
    isDelete:true,
    isView:true,
    module:"version"
},
rolepermissioncabinetMastermock:{
    isAdd:true,
    isEdit:true,
    isDelete:true,
    isView:false,
    module:"cabinet"
},
rolepermissionchannelmock:{
    isAdd:true,
    isEdit:true,
    isDelete:true,
    isView:false,
    module:"channel"
},
rolepermissionchanneltypemock:{
    isAdd:true,
    isEdit:true,
    isDelete:true,
    isView:false,
    module:"channeltype"
},
rolepermissiondenommock:{
    isAdd:true,
    isEdit:true,
    isDelete:true,
    isView:false,
    module:"denom"
},
rolepermissiondevcomplexitymock:{
    isAdd:true,
    isEdit:true,
    isDelete:true,
    isView:false,
    module:"devcomplexity"
},
rolepermissiondevefforttypemock:{
    isAdd:true,
    isEdit:true,
    isDelete:true,
    isView:false,
    module:"devefforttype"
},
rolepermissiondevtype1mock:{
    isAdd:true,
    isEdit:true,
    isDelete:true,
    isView:false,
    module:"devtype1"
},
rolepermissiondevtype2mock:{
    isAdd:true,
    isEdit:true,
    isDelete:true,
    isView:false,
    module:"devtype2"
},
rolepermissiondevtype3mock:{
    isAdd:true,
    isEdit:true,
    isDelete:true,
    isView:false,
    module:"devtype3"
},
rolepermissionemulationmock:{
    isAdd:true,
    isEdit:true,
    isDelete:true,
    isView:false,
    module:"emulation"
},
rolepermissionepp_refmock:{
    isAdd:true,
    isEdit:true,
    isDelete:true,
    isView:false,
    module:"epp_ref"
},
rolepermissiongamecomplexitymock:{
    isAdd:true,
    isEdit:true,
    isDelete:true,
    isView:false,
    module:"gamecomplexity"
},
rolepermissionfinancialyearmock:{
    isAdd:true,
    isEdit:true,
    isDelete:true,
    isView:false,
    module:"financialyear"
},
rolepermissiongravitymock:{
    isAdd:true,
    isEdit:true,
    isDelete:true,
    isView:false,
    module:"gravity"
},
rolepermissionmarketmock:{
    isAdd:true,
    isEdit:true,
    isDelete:true,
    isView:false,
    module:"market"
},
rolepermissionpoolmock:{
    isAdd:true,
    isEdit:true,
    isDelete:true,
    isView:false,
    module:"pool"
},
rolepermissionprodcat1mock:{
    isAdd:true,
    isEdit:true,
    isDelete:true,
    isView:false,
    module:"prodcat1"
},
rolepermissionprodcat2mock:{
    isAdd:true,
    isEdit:true,
    isDelete:true,
    isView:false,
    module:"prodcat2"
},
rolepermissionprodcat3mock:{
    isAdd:true,
    isEdit:true,
    isDelete:true,
    isView:false,
    module:"prodcat3"
},
rolepermissionproductgroupmock:{
    isAdd:true,
    isEdit:true,
    isDelete:true,
    isView:false,
    module:"productgroup"
},
rolepermissionproductbasketmock:{
    isAdd:true,
    isEdit:true,
    isDelete:true,
    isView:false,
    module:"productbasket"
},
rolepermissionquartermock:{
    isAdd:true,
    isEdit:true,
    isDelete:true,
    isView:false,
    module:"quarter"
},
rolepermissionregionmock:{
    isAdd:true,
    isEdit:true,
    isDelete:true,
    isView:false,
    module:"region" 
},
rolepermissionriskmock:{
    isAdd:true,
    isEdit:true,
    isDelete:true,
    isView:false,
    module:"risk" 
},
rolepermissionstatus1mock:{
    isAdd:true,
    isEdit:true,
    isDelete:true,
    isView:false,
    module:"status1" 
},
rolepermissionstatus2mock:{
    isAdd:true,
    isEdit:true,
    isDelete:true,
    isView:false,
    module:"status2" 
},
rolepermissionstatus3mock:{
    isAdd:true,
    isEdit:true,
    isDelete:true,
    isView:false,
    module:"status3" 
},
rolepermissionstudiomock:{
    isAdd:true,
    isEdit:true,
    isDelete:true,
    isView:false,
    module:"studio" 
},
rolepermissionthememock:{
    isAdd:true,
    isEdit:true,
    isDelete:true,
    isView:false,
    module:"them" 
},
rolepermissiontitlemock:{
    isAdd:true,
    isEdit:true,
    isDelete:true,
    isView:false,
    module:"title" 
},
rolepermissionvirdianlaunchmock:{
    isAdd:true,
    isEdit:true,
    isDelete:true,
    isView:false,
    module:"viridianlaunch" 
},
rolepermissionflagmock:{
    isAdd:true,
    isEdit:true,
    isDelete:true,
    isView:false,
    module:"flag" 
},
rolepermissionstudio2mock:{
    isAdd:true,
    isEdit:true,
    isDelete:true,
    isView:false,
    module:"studio2" 
},
rolepermissionstudiotypemock:{
    isAdd:true,
    isEdit:true,
    isDelete:true,
    isView:false,
    module:"studiotype" 
},
rolepermissionvideosteppermock:{
    isAdd:true,
    isEdit:true,
    isDelete:true,
    isView:false,
    module:"videostepper" 
},
rolepermissionmpworkflowmock:{
    isAdd:true,
    isEdit:true,
    isDelete:true,
    isView:false,
    module:"workflow" 
}
}]