export const rdapRolePermossionMockMaster = [{
    rolepermissionextrapinmock:{
        isAdd:true,
        isEdit:true,
        isDelete:true,
        isView:false,
        module:"ExtraPin"
    },modulename:""},{
    rolepermissionmanagepinmock:{
        isAdd:true,
        isEdit:true,
        isDelete:true,
        isView:false,
        module:"ManagePin"
    },modulename:""},{
    rolepermissiondependencymock:{
        isAdd:true,
        isEdit:true,
        isDelete:true,
        isView:false,
        module:"Dependency"
    },modulename:""},{
    rolepermissiontesterplanmock:{
        isAdd:true,
        isEdit:true,
        isDelete:true,
        isView:false,
        module:"TesterPlan"
    },modulename:""},{
    rolepermissionsetitemsmock:{
        isAdd:true,
        isEdit:true,
        isDelete:true,
        isView:false,
        module:"SetItem"
    },modulename:""},{
    rolepermissioncabinetmock:{
        isAdd:true,
        isEdit:true,
        isDelete:true,
        isView:false,
        module:"Cabinet"
    },modulename:""},{
    rolepermissionmilestonemock:{
        isAdd:true,
        isEdit:true,
        isDelete:true,
        isView:false,
        module:"Milestone"
    },modulename:""},{
    rolepermissionclaritymock:{
        isAdd:true,
        isEdit:true,
        isDelete:true,
        isView:false,
        module:"Clarity"
    },modulename:""},{
    rolepermissionlinkedpinmock:{
        isAdd:true,
        isEdit:true,
        isDelete:true,
        isView:false,
        module:"LinkedPin"
    },modulename:""},{
    rolepermissionimpactedpinmock:{
        isAdd:true,
        isEdit:true,
        isDelete:true,
        isView:false,
        module:"ImpactedPin"
    },modulename:""},{
    rolepermissionauditlogmock:{
        isAdd:true,
        isEdit:true,
        isDelete:true,
        isView:false,
        module:"AuditLog"
    },modulename:""},{
        data:{
        isAdd:false,
        isEdit:true,
        isDelete:true,
        isView:true,
        module:"version"
    },modulename:"version"},{
        data:{
        isAdd:false,
        isEdit:true,
        isDelete:false,
        isView:false,
        module:"cabinet"
    },modulename:"cabinet"},{
        data:{
        isAdd:true,
        isEdit:true,
        isDelete:true,
        isView:false,
        module:"channel"
    },modulename:"channel"},{
        data:{
        isAdd:true,
        isEdit:true,
        isDelete:true,
        isView:false,
        module:"channeltype"
    },modulename:"channeltype"},{
        data:{
        isAdd:true,
        isEdit:true,
        isDelete:true,
        isView:false,
        module:"denom"
    },modulename:"denom"},{
        data:{
        isAdd:true,
        isEdit:true,
        isDelete:true,
        isView:false,
        module:"devcomplexity"
    },modulename:"devcomplexity"},{
        data:{
        isAdd:true,
        isEdit:true,
        isDelete:true,
        isView:false,
        module:"devefforttype"
    },modulename:"devefforttype"},{
        data:{
        isAdd:true,
        isEdit:true,
        isDelete:true,
        isView:false,
        module:"devtype1"
    },modulename:"devtype1"},{
        data:{
        isAdd:true,
        isEdit:true,
        isDelete:true,
        isView:false,
        module:"devtype2"
    },modulename:"devtype2"},{
        data:{
        isAdd:true,
        isEdit:true,
        isDelete:true,
        isView:false,
        module:"devtype3"
    },modulename:"devtype3"},{
        data:{
        isAdd:true,
        isEdit:true,
        isDelete:true,
        isView:false,
        module:"emulation"
    },modulename:"emulation"},{
        data:{
        isAdd:true,
        isEdit:true,
        isDelete:true,
        isView:false,
        module:"epp_ref"
    },modulename:"epp_ref"},{
        data:{
        isAdd:true,
        isEdit:true,
        isDelete:true,
        isView:false,
        module:"gamecomplexity"
    },modulename:"gamecomplexity"},{
        data:{
        isAdd:true,
        isEdit:true,
        isDelete:true,
        isView:false,
        module:"financialyear"
    },modulename:"financialyear"},{
        data:{
        isAdd:true,
        isEdit:true,
        isDelete:true,
        isView:false,
        module:"gravity"
    },modulename:"gravity"},{
        data:{
        isAdd:true,
        isEdit:true,
        isDelete:true,
        isView:false,
        module:"market"
    },modulename:"market"},{
        data:{
        isAdd:true,
        isEdit:true,
        isDelete:true,
        isView:false,
        module:"pool"
    },modulename:"pool"},{
        data:{
        isAdd:true,
        isEdit:true,
        isDelete:true,
        isView:false,
        module:"prodcat1"
    },modulename:"prodcat1"},{
        data:{
        isAdd:true,
        isEdit:true,
        isDelete:true,
        isView:false,
        module:"prodcat2"
    },modulename:"prodcat2"},{
        data:{
        isAdd:true,
        isEdit:true,
        isDelete:true,
        isView:false,
        module:"prodcat3"
    },modulename:"prodcat3"},{
        data:{
        isAdd:true,
        isEdit:true,
        isDelete:true,
        isView:false,
        module:"productgroup"
    },modulename:"productgroup"},{
        data:{
        isAdd:true,
        isEdit:true,
        isDelete:true,
        isView:false,
        module:"productbasket"
    },modulename:"productbasket"},{
        data:{
        isAdd:true,
        isEdit:true,
        isDelete:true,
        isView:false,
        module:"quarter"
    },modulename:"quarter"},{
        data:{
        isAdd:true,
        isEdit:true,
        isDelete:true,
        isView:false,
        module:"region" 
    },modulename:"region"},{
        data:{
        isAdd:true,
        isEdit:true,
        isDelete:true,
        isView:false,
        module:"risk" 
    },modulename:"risk"},{
        data:{
        isAdd:true,
        isEdit:true,
        isDelete:true,
        isView:false,
        module:"status1" 
    },modulename:"status1"},{
        data:{
        isAdd:true,
        isEdit:true,
        isDelete:true,
        isView:false,
        module:"status2" 
    },modulename:"status2"},{
    rolepermissionstatus3mock:{
        isAdd:true,
        isEdit:true,
        isDelete:true,
        isView:false,
        module:"status3" 
    },modulename:"status3"},{
    rolepermissionstudiomock:{
        isAdd:true,
        isEdit:true,
        isDelete:true,
        isView:false,
        module:"studio" 
    },modulename:"studio"},{
        data:{
        isAdd:true,
        isEdit:true,
        isDelete:true,
        isView:false,
        module:"them" 
    },modulename:"them"},{
        data:{
        isAdd:true,
        isEdit:true,
        isDelete:true,
        isView:false,
        module:"title" 
    },modulename:"title"},{
    data:{
        isAdd:true,
        isEdit:true,
        isDelete:true,
        isView:false,
        module:"virdianlaunch" 
    },modulename:"virdianlaunch"},{
    data:{
        isAdd:true,
        isEdit:true,
        isDelete:true,
        isView:false,
        module:"flag" 
    },modulename:"flag"},{
    data:{
        isAdd:true,
        isEdit:true,
        isDelete:true,
        isView:false,
        module:"studio2" 
    },modulename:"studio2"},{
    data:{
        isAdd:true,
        isEdit:true,
        isDelete:true,
        isView:false,
        module:"studiotype" 
    },modulename:"studiotype"},{
    data:{
        isAdd:true,
        isEdit:true,
        isDelete:true,
        isView:false,
        module:"videostepper" 
    },modulename:"videostepper"
    }]